// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// marginCombo
NumericMatrix marginCombo(NumericVector alphavec, NumericMatrix mc);
RcppExport SEXP _lcopula_marginCombo(SEXP alphavecSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mc(mcSEXP);
    rcpp_result_gen = Rcpp::wrap(marginCombo(alphavec, mc));
    return rcpp_result_gen;
END_RCPP
}
// dirspecdens
NumericVector dirspecdens(NumericVector param, NumericMatrix dat, int d, bool transform);
RcppExport SEXP _lcopula_dirspecdens(SEXP paramSEXP, SEXP datSEXP, SEXP dSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type transform(transformSEXP);
    rcpp_result_gen = Rcpp::wrap(dirspecdens(param, dat, d, transform));
    return rcpp_result_gen;
END_RCPP
}
// negdirspecdens
NumericVector negdirspecdens(NumericVector param, NumericMatrix dat, int d, bool transform);
RcppExport SEXP _lcopula_negdirspecdens(SEXP paramSEXP, SEXP datSEXP, SEXP dSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type transform(transformSEXP);
    rcpp_result_gen = Rcpp::wrap(negdirspecdens(param, dat, d, transform));
    return rcpp_result_gen;
END_RCPP
}
// ctspecdens
NumericVector ctspecdens(NumericVector param, NumericMatrix dat, bool transform);
RcppExport SEXP _lcopula_ctspecdens(SEXP paramSEXP, SEXP datSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< bool >::type transform(transformSEXP);
    rcpp_result_gen = Rcpp::wrap(ctspecdens(param, dat, transform));
    return rcpp_result_gen;
END_RCPP
}
