// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dens_const
NumericVector dens_const(NumericVector alpha, NumericVector rho);
RcppExport SEXP lcopula_dens_const(SEXP alphaSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    __result = Rcpp::wrap(dens_const(alpha, rho));
    return __result;
END_RCPP
}
// b_const
NumericVector b_const(NumericVector index, NumericVector rho);
RcppExport SEXP lcopula_b_const(SEXP indexSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    __result = Rcpp::wrap(b_const(index, rho));
    return __result;
END_RCPP
}
// spectraldensity
NumericVector spectraldensity(NumericVector w, NumericVector alphavec, NumericVector rho);
RcppExport SEXP lcopula_spectraldensity(SEXP wSEXP, SEXP alphavecSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    __result = Rcpp::wrap(spectraldensity(w, alphavec, rho));
    return __result;
END_RCPP
}
// marginCombo
NumericMatrix marginCombo(NumericVector alphavec, NumericMatrix mc);
RcppExport SEXP lcopula_marginCombo(SEXP alphavecSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mc(mcSEXP);
    __result = Rcpp::wrap(marginCombo(alphavec, mc));
    return __result;
END_RCPP
}
